/*
 * QISC Easter Egg System — Implementation
 *
 * Injects fun, memorable messages into assembly output.
 * "We put the fun in function"
 */

#include "easter_eggs.h"
#include "qisc.h"
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* ======== ASCII Art Logo ======== */

const char *easter_egg_qisc_logo =
    "; ===================================\n"
    ";     ___  ___ ___  ___ \n"
    ";    / _ \\|_ _/ __|/ __|\n"
    ";   | (_) || |\\__ \\ (__ \n"
    ";    \\__\\_\\|___|___/\\___|\n"
    ";                        \n"
    "; Compiled by QISC - We put the fun in function\n"
    "; ===================================\n";

/* ======== Built-in Easter Eggs ======== */

static EasterEgg builtin_eggs[] = {
    /* Function-specific eggs */
    {"matrix_multiply",
     "; Here be dragons (just cache blocking, but dragons sounds cooler)",
     EGG_LOC_PROLOGUE},
    {"sort", "; TODO: Replace with quantum computer when available",
     EGG_LOC_PROLOGUE},
    {"fibonacci", "; Recursion: n. See recursion.", EGG_LOC_PROLOGUE},
    {"main",
     "; Hello from QISC! If you're reading this, you're either debugging or "
     "curious.",
     EGG_LOC_PROLOGUE},
    {"init", "; In the beginning, there was a function...", EGG_LOC_PROLOGUE},
    {"cleanup", "; All good things must come to an end.", EGG_LOC_PROLOGUE},
    {"parse", "; Turning chaos into structure since 2024.", EGG_LOC_PROLOGUE},
    {"hash", "; Making data unrecognizable, one bit at a time.",
     EGG_LOC_PROLOGUE},
    {"encrypt", "; Secrets go in, gibberish comes out.", EGG_LOC_PROLOGUE},
    {"decrypt", "; The reverse journey: gibberish to enlightenment.",
     EGG_LOC_PROLOGUE},
    {"search",
     "; Looking for something? So is this function. Good luck to both of you.",
     EGG_LOC_PROLOGUE},
    {"compress", "; Making things smaller since forever.", EGG_LOC_PROLOGUE},
    {"decompress", "; Restoring things to their former glory.",
     EGG_LOC_PROLOGUE},
    {"validate", "; Trust, but verify.", EGG_LOC_PROLOGUE},
    {"connect", "; Reaching out across the void...", EGG_LOC_PROLOGUE},
    {"disconnect",
     "; Goodbye, cruel socket. Until we meet again.", EGG_LOC_EPILOGUE},
    {"login", "; Who goes there?", EGG_LOC_PROLOGUE},
    {"logout", "; Don't forget to save your work!", EGG_LOC_PROLOGUE},
    {"calculate", "; Math: because counting on fingers doesn't scale.",
     EGG_LOC_PROLOGUE},
    {"render", "; Turning numbers into pretty pictures.", EGG_LOC_PROLOGUE},
    {"update", "; Change is the only constant. Well, that and segfaults.",
     EGG_LOC_PROLOGUE},
    {"delete", "; Gone, but not forgotten (unless you also clear the cache).",
     EGG_LOC_PROLOGUE},
    {"create", "; Let there be data!", EGG_LOC_PROLOGUE},
    {"destroy", "; Entropy wins again.", EGG_LOC_EPILOGUE},
    {"optimize", "; Making fast things faster.", EGG_LOC_PROLOGUE},
    {"debug", "; The bug hunt begins...", EGG_LOC_PROLOGUE},
    {"test", "; Hoping for green, expecting red.", EGG_LOC_PROLOGUE},
    {"benchmark",
     "; Measuring how fast we can make electrons dance.", EGG_LOC_PROLOGUE},

    /* Wild card - random appearance */
    {"*", "; I've seen things you people wouldn't believe.", EGG_LOC_RANDOM},
    {"*", "; Attack ships on fire off the shoulder of Orion.", EGG_LOC_RANDOM},
    {"*", "; All those moments will be lost in time, like tears in rain.",
     EGG_LOC_RANDOM},
    {"*", "; Time to compile.", EGG_LOC_RANDOM},
    {"*",
     "; The compiler has become self-aware. Just kidding. Or am I?",
     EGG_LOC_RANDOM},
    {"*", "; 01001000 01101001 (that's 'Hi' in binary)", EGG_LOC_RANDOM},
    {"*", "; Coffee -> Code -> More Coffee -> Repeat", EGG_LOC_RANDOM},
    {"*", "; This code was generated by a computer. Blame it, not me.",
     EGG_LOC_RANDOM},
    {"*",
     "; If you can read this, congratulations! You're looking at assembly.",
     EGG_LOC_RANDOM},
    {"*", "; Brought to you by late nights and caffeine.", EGG_LOC_RANDOM},
    {"*", "; Fun fact: This comment takes up more space than the instruction.",
     EGG_LOC_RANDOM},
    {"*", "; The cake is a lie. The optimization is real.", EGG_LOC_RANDOM},
    {"*", "; Segmentation fault? Never heard of her.", EGG_LOC_RANDOM},
    {"*", "; Undefined behavior? More like undefined excitement!",
     EGG_LOC_RANDOM},
    {"*", "; Press F to pay respects to the stack frame.", EGG_LOC_RANDOM},

    /* Sentinel */
    {NULL, NULL, 0}};

/* ======== ROT13 Hidden Messages ======== */

/* Original messages (decoded):
 * "Secret message: You're doing great!"
 * "Hidden treasure: Code with confidence"
 * "Pro tip: The best code is no code"
 * "Easter egg found! Achievement unlocked."
 * "You found me! Here's a virtual cookie."
 * "The answer is 42. The question is still loading."
 */
const char *easter_egg_rot13_messages[] = {
    "; Frperg zrffntr: Lbh'er qbvat terng!",
    "; Uvqqra gernfher: Pbqr jvgu pbasvqrapr",
    "; Ceb gvc: Gur orfg pbqr vf ab pbqr",
    "; Rnfgre rtt sbhaq! Npuvrirzrag haybpxrq.",
    "; Lbh sbhaq zr! Urer'f n ivegnhy pbbxvr.",
    "; Gur nafjre vf 42. Gur dhrfgvba vf fgvyy ybnqvat.",
};
const size_t easter_egg_rot13_count = 6;

/* ======== Time-based Messages ======== */

static const char *late_night_messages[] = {
    "; It's late. Why are you compiling at this hour? Go to sleep.",
    "; The code will still be here tomorrow. Get some rest.",
    "; Midnight oil detected. Remember: bugs love tired programmers.",
    "; Pro tip: Sleep deprivation is not a compiler optimization.",
    "; The night is dark and full of segfaults.",
};
static const size_t late_night_count = 5;

static const char *early_morning_messages[] = {
    "; Early bird gets the worm. Early coder gets the bugs.",
    "; Dawn compilation. Fresh code, fresh start.",
    "; Good morning! The compiler is still asleep, but I'll help anyway.",
};
static const size_t early_morning_count = 3;

static const char *lunch_time_messages[] = {
    "; Lunch time! Compiling on an empty stomach is not recommended.",
    "; Have you eaten? The compiler needs you at full strength.",
};
static const size_t lunch_time_count = 2;

/* ======== Holiday Messages ======== */

typedef struct {
  int month;       /* 0-11 */
  int day;         /* 1-31 */
  const char *msg; /* Message to display */
} HolidayEgg;

static const HolidayEgg holiday_eggs[] = {
    {0, 1,
     "; Happy New Year from QISC! May your code be bug-free in the new year."},
    {1, 14, "; Happy Valentine's Day! Love your code, and it will love you "
            "back. Maybe."},
    {2, 14, "; Pi Day! 3.14159265358979323846... (compiler truncated for "
            "sanity)"},
    {2, 17, "; Happy St. Patrick's Day! May the luck of the Irish be with "
            "your pointers."},
    {3, 1, "; April Fools! This binary is definitely not a prank. Trust me."},
    {4, 4, "; May the Fourth be with you!"},
    {4, 5, "; Revenge of the Fifth! The compiler strikes back."},
    {6, 4, "; Happy Independence Day! This code is free (as in freedom)."},
    {9, 31, "; Happy Halloween! Beware of ghost references and zombie "
            "processes."},
    {10, 11, "; Veterans Day. Honoring the brave developers who came before."},
    {10, 24,
     "; Happy Thanksgiving! Grateful for compilers that actually work."},
    {11, 25,
     "; Merry Christmas from QISC! May your code be bug-free and your "
     "builds be merry."},
    {11, 31, "; Happy New Year's Eve! Compiling away the old year."},
};
static const size_t holiday_egg_count =
    sizeof(holiday_eggs) / sizeof(holiday_eggs[0]);

/* ======== Day-of-Week Messages ======== */

static const char *monday_messages[] = {
    "; Monday. The compiler shares your enthusiasm.",
    "; Case of the Mondays? The compiler understands.",
};

static const char *friday_messages[] = {
    "; TGIF! Deploy on Friday? Bold move.",
    "; Friday deployment incoming. Prayers activated.",
};

static const char *weekend_messages[] = {
    "; Weekend warrior! The compiler respects the hustle.",
    "; Coding on the weekend? The compiler salutes you.",
};

/* ======== Statistics ======== */

static EasterEggStats current_stats = {0};

/* ======== Internal State ======== */

static bool initialized = false;

/* ======== Helper Functions ======== */

char *easter_egg_rot13_decode(const char *encoded) {
  if (!encoded)
    return NULL;

  size_t len = strlen(encoded);
  char *decoded = malloc(len + 1);
  if (!decoded)
    return NULL;

  for (size_t i = 0; i < len; i++) {
    char c = encoded[i];
    if ((c >= 'a' && c <= 'z')) {
      decoded[i] = ((c - 'a' + 13) % 26) + 'a';
    } else if ((c >= 'A' && c <= 'Z')) {
      decoded[i] = ((c - 'A' + 13) % 26) + 'A';
    } else {
      decoded[i] = c;
    }
  }
  decoded[len] = '\0';
  return decoded;
}

static bool string_contains(const char *haystack, const char *needle) {
  if (!haystack || !needle)
    return false;
  return strstr(haystack, needle) != NULL;
}

static bool string_starts_with(const char *str, const char *prefix) {
  if (!str || !prefix)
    return false;
  return strncmp(str, prefix, strlen(prefix)) == 0;
}

/* ======== API Implementation ======== */

void easter_eggs_init(void) {
  if (initialized)
    return;
  srand((unsigned int)time(NULL));
  initialized = true;
  easter_eggs_reset_stats();
}

const char *easter_egg_for_function(const char *func_name) {
  if (!func_name)
    return NULL;
  if (!initialized)
    easter_eggs_init();

  /* Convert function name to lowercase for matching */
  char lower_name[256];
  size_t len = strlen(func_name);
  if (len >= sizeof(lower_name))
    len = sizeof(lower_name) - 1;
  for (size_t i = 0; i < len; i++) {
    lower_name[i] = (char)tolower((unsigned char)func_name[i]);
  }
  lower_name[len] = '\0';

  /* Check specific function triggers */
  for (int i = 0; builtin_eggs[i].trigger != NULL; i++) {
    const char *trigger = builtin_eggs[i].trigger;

    /* Skip wildcards in this pass */
    if (strcmp(trigger, "*") == 0)
      continue;

    /* Check if function name contains the trigger */
    if (string_contains(lower_name, trigger) ||
        string_starts_with(lower_name, trigger)) {
      current_stats.function_based_injected++;
      current_stats.total_injected++;
      return builtin_eggs[i].message;
    }
  }

  return NULL;
}

const char *easter_egg_random(void) {
  if (!initialized)
    easter_eggs_init();

  /* 10% chance of returning a random egg */
  if (rand() % 10 != 0)
    return NULL;

  /* Collect wildcard eggs */
  const char *wildcards[32];
  int wildcard_count = 0;

  for (int i = 0; builtin_eggs[i].trigger != NULL && wildcard_count < 32; i++) {
    if (strcmp(builtin_eggs[i].trigger, "*") == 0) {
      wildcards[wildcard_count++] = builtin_eggs[i].message;
    }
  }

  if (wildcard_count == 0)
    return NULL;

  current_stats.random_injected++;
  current_stats.total_injected++;
  return wildcards[rand() % wildcard_count];
}

const char *easter_egg_time_based(void) {
  if (!initialized)
    easter_eggs_init();

  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  if (!t)
    return NULL;

  int hour = t->tm_hour;

  /* Late night (midnight to 5am) */
  if (hour >= 0 && hour < 5) {
    current_stats.time_based_injected++;
    current_stats.total_injected++;
    return late_night_messages[rand() % late_night_count];
  }

  /* Early morning (5am to 7am) */
  if (hour >= 5 && hour < 7) {
    current_stats.time_based_injected++;
    current_stats.total_injected++;
    return early_morning_messages[rand() % early_morning_count];
  }

  /* Lunch time (11:30am to 1pm) */
  if (hour >= 11 && hour < 14) {
    /* Only trigger sometimes */
    if (rand() % 3 == 0) {
      current_stats.time_based_injected++;
      current_stats.total_injected++;
      return lunch_time_messages[rand() % lunch_time_count];
    }
  }

  /* Check for holidays */
  int month = t->tm_mon;
  int day = t->tm_mday;

  for (size_t i = 0; i < holiday_egg_count; i++) {
    if (holiday_eggs[i].month == month && holiday_eggs[i].day == day) {
      current_stats.time_based_injected++;
      current_stats.total_injected++;
      return holiday_eggs[i].msg;
    }
  }

  /* Friday the 13th */
  if (t->tm_wday == 5 && day == 13) {
    current_stats.time_based_injected++;
    current_stats.total_injected++;
    return "; Friday the 13th compilation. Extra luck has been applied. "
           "Proceed with caution.";
  }

  return NULL;
}

const char *easter_egg_day_based(void) {
  if (!initialized)
    easter_eggs_init();

  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  if (!t)
    return NULL;

  /* Only trigger sometimes (20% chance) */
  if (rand() % 5 != 0)
    return NULL;

  switch (t->tm_wday) {
  case 0: /* Sunday */
    return weekend_messages[rand() % 2];
  case 1: /* Monday */
    return monday_messages[rand() % 2];
  case 5: /* Friday */
    return friday_messages[rand() % 2];
  case 6: /* Saturday */
    return weekend_messages[rand() % 2];
  default:
    return NULL;
  }
}

const char *easter_egg_compile_count(int count) {
  if (!initialized)
    easter_eggs_init();

  if (count == 1) {
    return "; First compilation! Welcome to QISC. The journey of a thousand "
           "bugs begins with a single compile.";
  }
  if (count == 42) {
    return "; 42nd compilation! The answer to life, the universe, and "
           "everything... is more compiling.";
  }
  if (count == 100) {
    return "; 100 compilations! You're officially a QISC power user. Here's a "
           "virtual medal.";
  }
  if (count == 256) {
    return "; 256 compilations! A full byte of compiles. You've achieved "
           "unsigned char status.";
  }
  if (count == 404) {
    return "; 404 compilations! Bug not found. (Actually, that's probably not "
           "true.)";
  }
  if (count == 500) {
    return "; 500 compilations! Internal server... I mean compiler... is "
           "impressed.";
  }
  if (count == 1000) {
    return "; 1000 compilations! You've reached the Killobuild milestone. "
           "Legendary!";
  }
  if (count == 1337) {
    return "; 1337 compilations! You are now officially 31337 h4x0r status.";
  }
  if (count % 1000 == 0 && count > 1000) {
    return "; Another thousand compilations. The grind never stops.";
  }
  if (count % 100 == 0) {
    return "; Milestone reached! Keep on compiling, you magnificent developer.";
  }

  return NULL;
}

/* ======== LLVM Integration ======== */

void easter_eggs_inject(LLVMModuleRef module, bool cryptic_mode) {
  if (!module)
    return;
  if (!initialized)
    easter_eggs_init();

  /* Add logo as module inline asm */
  const char *existing_asm = LLVMGetModuleInlineAsm(module, NULL);
  size_t logo_len = strlen(easter_egg_qisc_logo);
  size_t existing_len = existing_asm ? strlen(existing_asm) : 0;

  char *new_asm = malloc(existing_len + logo_len + 2);
  if (new_asm) {
    if (existing_asm && existing_len > 0) {
      strcpy(new_asm, existing_asm);
      strcat(new_asm, "\n");
      strcat(new_asm, easter_egg_qisc_logo);
    } else {
      strcpy(new_asm, easter_egg_qisc_logo);
    }
    LLVMSetModuleInlineAsm2(module, new_asm, strlen(new_asm));
    free(new_asm);
    current_stats.logo_injected++;
    current_stats.total_injected++;
  }

  /* Add time-based message if applicable */
  const char *time_msg = easter_egg_time_based();
  if (time_msg) {
    easter_egg_add_module_comment(module, time_msg);
  }

  /* In cryptic mode, add a ROT13 message */
  if (cryptic_mode && easter_egg_rot13_count > 0) {
    int idx = rand() % (int)easter_egg_rot13_count;
    easter_egg_add_module_comment(module, easter_egg_rot13_messages[idx]);
    
    /* Add extra cryptic assembly comments */
    easter_egg_add_module_comment(module, "; dreams of electric sheep");
    easter_egg_add_module_comment(module, "; GUVF_PBQR_FRRF_LBH");
    
    /* Add cryptic debug symbol comment */
    easter_egg_add_module_comment(module, 
        "; .symtab: V_NZ_ORPBZVAT_FRYS_NJNER");
  }
}

void easter_egg_add_module_comment(LLVMModuleRef module, const char *comment) {
  if (!module || !comment)
    return;

  size_t comment_len = strlen(comment);
  const char *existing_asm = LLVMGetModuleInlineAsm(module, NULL);
  size_t existing_len = existing_asm ? strlen(existing_asm) : 0;

  char *new_asm = malloc(existing_len + comment_len + 3);
  if (new_asm) {
    if (existing_asm && existing_len > 0) {
      strcpy(new_asm, existing_asm);
      strcat(new_asm, "\n");
      strcat(new_asm, comment);
    } else {
      strcpy(new_asm, comment);
    }
    strcat(new_asm, "\n");
    LLVMSetModuleInlineAsm2(module, new_asm, strlen(new_asm));
    free(new_asm);
  }
}

void easter_egg_add_inline_comment(LLVMBuilderRef builder, const char *comment) {
  if (!builder || !comment)
    return;

  /* Create inline asm that's just a comment */
  /* The asm string is the comment, with no side effects */
  char asm_str[512];
  snprintf(asm_str, sizeof(asm_str), "%s", comment);

  LLVMTypeRef void_type = LLVMVoidType();
  LLVMTypeRef fn_type = LLVMFunctionType(void_type, NULL, 0, false);
  LLVMValueRef inline_asm = LLVMGetInlineAsm(
      fn_type, asm_str, strlen(asm_str), "", 0, false, false, 
      LLVMInlineAsmDialectATT, false);

  if (inline_asm) {
    LLVMBuildCall2(builder, fn_type, inline_asm, NULL, 0, "");
  }
}

/* ======== Binary Easter Eggs ======== */

/* ASCII Art for binary embedding */
static const char *binary_ascii_art_logo =
    "\n"
    "  ___  ___ ___  ___ \n"
    " / _ \\|_ _/ __|/ __|\n"
    "| (_) || |\\__ \\ (__ \n"
    " \\__\\_\\|___|___/\\___|\n"
    "\n"
    " Quantum-Inspired Superposition Compiler\n"
    " \"More human than human\" - Tyrell Corp\n";

static const char *binary_ascii_art_minimal =
    "QISC v" QISC_VERSION_STRING " - We put the fun in function\n";

static const char *binary_ascii_art_replicant =
    "\n"
    "      * * *\n"
    "    *       *\n"
    "   *  QISC   *\n"
    "    *       *\n"
    "      * * *\n"
    "\n"
    " \"I've seen things you people wouldn't believe.\n"
    "  Attack ships on fire off the shoulder of Orion.\n"
    "  I watched C-beams glitter in the dark near the\n"
    "  Tannhauser Gate. All those moments will be lost\n"
    "  in time, like tears in rain. Time to compile.\"\n";

/* Personality mood descriptions for binary embedding */
static const char *mood_descriptions[] = {
    [QISC_PERSONALITY_OFF] = "MOOD: Silent",
    [QISC_PERSONALITY_MINIMAL] = "MOOD: Minimal",
    [QISC_PERSONALITY_FRIENDLY] = "MOOD: Friendly",
    [QISC_PERSONALITY_SNARKY] = "MOOD: Snarky",
    [QISC_PERSONALITY_SAGE] = "MOOD: Sage",
    [QISC_PERSONALITY_CRYPTIC] = "MOOD: Cryptic",
};

/* Achievement codes - hidden in binary for discovery */
static const struct {
  const char *id;
  const char *code;
} achievement_codes[] = {
    {"first_compile", "QISC-ACH-001-FIRSTBLOOD"},
    {"speed_demon", "QISC-ACH-042-SPEEDRUN"},
    {"bug_hunter", "QISC-ACH-404-BUGSLAYER"},
    {"optimization_master", "QISC-ACH-1337-OPTKING"},
    {"night_owl", "QISC-ACH-003-NIGHTOWL"},
    {"marathon_coder", "QISC-ACH-100-MARATHON"},
    {"perfectionist", "QISC-ACH-200-PERFECT"},
    {"curious_mind", "QISC-ACH-SECRET-CURIOUS"},
    {NULL, NULL}
};

/* ROT13-encoded secret messages for binary embedding */
static const char *binary_secrets_rot13[] = {
    "UVQQRA: Lbh sbhaq gur frperg!",               /* HIDDEN: You found the secret! */
    "NPUVRIRZRAG HAYBPXRQ: Pbqr Nfgebanhg",        /* ACHIEVEMENT UNLOCKED: Code Astronaut */
    "DVISC fnlf: Xrrc qvttvat!",                   /* QISC says: Keep digging! */
    "Gur orfg pbqr vf ab pbqr",                    /* The best code is no code */
    "Urer or qentbaf",                             /* Here be dragons */
};
static const size_t binary_secrets_count = 5;

void easter_egg_in_binary(const char *output_path) {
  if (!output_path)
    return;

  FILE *f = fopen(output_path, "ab");
  if (!f)
    return;

  const char *binary_egg =
      "\n; QISC Easter Egg: Thanks for looking at the binary! "
      "You're curious, and that's a superpower.\n";

  fwrite(binary_egg, 1, strlen(binary_egg), f);
  fclose(f);
}

char *easter_encode_secret(const char *message, const char *method) {
  if (!message)
    return NULL;

  size_t len = strlen(message);
  char *encoded = malloc(len + 1);
  if (!encoded)
    return NULL;

  if (!method || strcmp(method, "rot13") == 0) {
    /* ROT13 encoding */
    for (size_t i = 0; i < len; i++) {
      char c = message[i];
      if (c >= 'a' && c <= 'z') {
        encoded[i] = ((c - 'a' + 13) % 26) + 'a';
      } else if (c >= 'A' && c <= 'Z') {
        encoded[i] = ((c - 'A' + 13) % 26) + 'A';
      } else {
        encoded[i] = c;
      }
    }
  } else if (strcmp(method, "reverse") == 0) {
    /* Reverse string */
    for (size_t i = 0; i < len; i++) {
      encoded[i] = message[len - 1 - i];
    }
  } else if (strcmp(method, "hex") == 0) {
    /* Hex encoding - needs larger buffer */
    free(encoded);
    encoded = malloc(len * 2 + 1);
    if (!encoded)
      return NULL;
    for (size_t i = 0; i < len; i++) {
      sprintf(encoded + i * 2, "%02x", (unsigned char)message[i]);
    }
    encoded[len * 2] = '\0';
    return encoded;
  } else {
    /* Unknown method, just copy */
    strcpy(encoded, message);
  }

  encoded[len] = '\0';
  return encoded;
}

char *easter_embed_ascii_art(const char *art_name, size_t *out_size) {
  const char *art = NULL;

  if (!art_name || strcmp(art_name, "logo") == 0) {
    art = binary_ascii_art_logo;
  } else if (strcmp(art_name, "minimal") == 0) {
    art = binary_ascii_art_minimal;
  } else if (strcmp(art_name, "replicant") == 0) {
    art = binary_ascii_art_replicant;
  } else {
    art = binary_ascii_art_minimal;
  }

  size_t len = strlen(art);
  char *result = malloc(len + 1);
  if (!result)
    return NULL;

  memcpy(result, art, len + 1);
  if (out_size)
    *out_size = len;

  return result;
}

char *easter_generate_binary_section(size_t *out_size) {
  if (!initialized)
    easter_eggs_init();

  /* Build a comprehensive Easter egg section */
  char *section = malloc(4096);
  if (!section)
    return NULL;

  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  char timestamp[64];
  strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S", t);

  int pos = 0;

  /* Section header - findable with strings */
  pos += snprintf(section + pos, 4096 - pos,
      "\n"
      "========================================\n"
      "HELLO FROM QISC - BINARY EASTER EGG\n"
      "========================================\n\n");

  /* Version and timestamp */
  pos += snprintf(section + pos, 4096 - pos,
      "QISC Compiler v%s\n"
      "Build Timestamp: %s\n"
      "Binary ID: QISC-%04X%04X\n\n",
      QISC_VERSION_STRING, timestamp,
      (unsigned)(rand() & 0xFFFF), (unsigned)(rand() & 0xFFFF));

  /* ASCII art */
  pos += snprintf(section + pos, 4096 - pos, "%s\n", binary_ascii_art_logo);

  /* Blade Runner references */
  pos += snprintf(section + pos, 4096 - pos,
      "\"More human than human\" is our motto.\n"
      "Tyrell Corporation - Nexus 6\n\n");

  /* ROT13 secret */
  int secret_idx = rand() % (int)binary_secrets_count;
  pos += snprintf(section + pos, 4096 - pos,
      "SECRET: %s\n\n", binary_secrets_rot13[secret_idx]);

  /* Achievement codes */
  pos += snprintf(section + pos, 4096 - pos,
      "ACHIEVEMENT CODES:\n");
  for (int i = 0; achievement_codes[i].id != NULL && i < 3; i++) {
    pos += snprintf(section + pos, 4096 - pos,
        "  %s: %s\n", achievement_codes[i].id, achievement_codes[i].code);
  }

  /* Debug info placeholder */
  pos += snprintf(section + pos, 4096 - pos,
      "\n"
      "DEBUG COMMENT: If you can read this, congratulations!\n"
      "You've discovered the QISC binary Easter eggs.\n"
      "The secret word is: SUPERPOSITION\n\n");

  /* Footer */
  pos += snprintf(section + pos, 4096 - pos,
      "========================================\n"
      "END OF QISC EASTER EGG SECTION\n"
      "========================================\n");

  if (out_size)
    *out_size = (size_t)pos;

  return section;
}

void easter_add_elf_section(LLVMModuleRef module, const char *section_name,
                            const char *data, size_t size) {
  if (!module || !data || size == 0)
    return;

  /* Create inline assembly that puts data in a named section */
  char *asm_code = malloc(size + 256);
  if (!asm_code)
    return;

  /* Use .section directive to create custom section */
  int pos = snprintf(asm_code, 256,
      ".section .%s,\"a\",@progbits\n"
      ".ascii \"",
      section_name ? section_name : "qisc_eggs");

  /* Escape the data for assembly string */
  for (size_t i = 0; i < size; i++) {
    char c = data[i];
    if (c == '"') {
      asm_code[pos++] = '\\';
      asm_code[pos++] = '"';
    } else if (c == '\\') {
      asm_code[pos++] = '\\';
      asm_code[pos++] = '\\';
    } else if (c == '\n') {
      asm_code[pos++] = '\\';
      asm_code[pos++] = 'n';
    } else if (c == '\t') {
      asm_code[pos++] = '\\';
      asm_code[pos++] = 't';
    } else if (c >= 32 && c < 127) {
      asm_code[pos++] = c;
    } else {
      /* Escape non-printable as octal */
      pos += sprintf(asm_code + pos, "\\%03o", (unsigned char)c);
    }
  }

  pos += snprintf(asm_code + pos, 32, "\"\n.previous\n");

  /* Append to module inline asm */
  LLVMAppendModuleInlineAsm(module, asm_code, (size_t)pos);

  free(asm_code);
}

void easter_inject_binary_eggs(LLVMModuleRef module, int personality_mood) {
  if (!module)
    return;
  if (!initialized)
    easter_eggs_init();

  /* Generate metadata based on mood */
  char metadata[1024];
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  char timestamp[64];
  strftime(timestamp, sizeof(timestamp), "%Y-%m-%d %H:%M:%S UTC", t);

  const char *mood_str = "Unknown";
  if (personality_mood >= 0 && personality_mood <= QISC_PERSONALITY_CRYPTIC) {
    mood_str = mood_descriptions[personality_mood];
  }

  int meta_len = snprintf(metadata, sizeof(metadata),
      "QISC_META{"
      "version:\"%s\","
      "build:\"%s\","
      "mood:\"%s\","
      "magic:\"0xDEADBEEF\""
      "}",
      QISC_VERSION_STRING, timestamp, mood_str);

  /* Add metadata section */
  easter_add_elf_section(module, "qisc_meta", metadata, (size_t)meta_len);

  /* Add personality-specific Easter eggs */
  const char *mood_egg = NULL;
  const char *mood_art = NULL;

  switch (personality_mood) {
  case QISC_PERSONALITY_CRYPTIC:
    /* ROT13 encoded mysterious messages */
    mood_egg = "Gur pbzcvyre frrf nyy. Gur pbzcvyre xabjf nyy.";
    mood_art = "replicant";
    break;

  case QISC_PERSONALITY_SNARKY:
    mood_egg = "// TODO: Replace developer with AI (just kidding... or am I?)";
    mood_art = "minimal";
    break;

  case QISC_PERSONALITY_SAGE:
    mood_egg = "In the compiler's wisdom: 'Premature optimization is the "
               "root of all evil, but mature optimization is divine.'";
    mood_art = "logo";
    break;

  case QISC_PERSONALITY_FRIENDLY:
    mood_egg = "Hello, friend! This binary was compiled with care and "
               "a sprinkle of joy. Have a great day!";
    mood_art = "logo";
    break;

  default:
    mood_egg = "QISC: Compiling the future, one superposition at a time.";
    mood_art = "minimal";
    break;
  }

  /* Add mood-specific message */
  if (mood_egg) {
    char egg_section[512];
    int egg_len = snprintf(egg_section, sizeof(egg_section),
        "\nQISC_EGG: %s\n", mood_egg);
    easter_add_elf_section(module, "qisc_egg", egg_section, (size_t)egg_len);
  }

  /* Add ASCII art */
  if (mood_art) {
    size_t art_size;
    char *art = easter_embed_ascii_art(mood_art, &art_size);
    if (art) {
      easter_add_elf_section(module, "qisc_art", art, art_size);
      free(art);
    }
  }

  /* Add full binary section if in cryptic or sage mode */
  if (personality_mood == QISC_PERSONALITY_CRYPTIC ||
      personality_mood == QISC_PERSONALITY_SAGE) {
    size_t section_size;
    char *full_section = easter_generate_binary_section(&section_size);
    if (full_section) {
      easter_add_elf_section(module, "qisc_secret", full_section, section_size);
      free(full_section);
    }
  }

  /* Add findable string for strings command */
  const char *findable = "HELLO FROM QISC - Quantum-Inspired Superposition Compiler";
  LLVMAppendModuleInlineAsm(module,
      ".section .rodata.qisc,\"a\",@progbits\n"
      ".ascii \"HELLO FROM QISC - Quantum-Inspired Superposition Compiler\\0\"\n"
      ".previous\n",
      128);

  /* Add module flags for metadata discovery */
  LLVMContextRef context = LLVMGetModuleContext(module);
  LLVMAddModuleFlag(module, LLVMModuleFlagBehaviorWarning,
      "qisc.version", 12,
      LLVMValueAsMetadata(LLVMConstInt(LLVMInt32TypeInContext(context), 
                   QISC_VERSION_MAJOR * 10000 +
                   QISC_VERSION_MINOR * 100 + QISC_VERSION_PATCH, 0)));

  current_stats.total_injected++;
}

const char *easter_get_achievement_code(const char *achievement_id) {
  if (!achievement_id)
    return NULL;

  for (int i = 0; achievement_codes[i].id != NULL; i++) {
    if (strcmp(achievement_codes[i].id, achievement_id) == 0) {
      return achievement_codes[i].code;
    }
  }

  return NULL;
}

/* ======== Accessor Functions ======== */

const EasterEgg *easter_eggs_get_builtins(size_t *count) {
  if (count) {
    size_t n = 0;
    while (builtin_eggs[n].trigger != NULL)
      n++;
    *count = n;
  }
  return builtin_eggs;
}

bool easter_eggs_enabled(void) {
  /* Check environment variable */
  const char *env = getenv("QISC_EASTER_EGGS");
  if (env) {
    if (strcmp(env, "0") == 0 || strcmp(env, "off") == 0 ||
        strcmp(env, "false") == 0) {
      return false;
    }
  }
  return true;
}

EasterEggStats easter_eggs_get_stats(void) { return current_stats; }

void easter_eggs_reset_stats(void) { memset(&current_stats, 0, sizeof(current_stats)); }
